[package]
name = "axum_mistral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
axum = { version = "0.6.20", features = ["ws", "macros"] }
candle-core = { version = "0.3.1", features = ["cuda"] }
candle-examples = "0.3.1"
candle-nn = "0.3.1"
candle-transformers = { version = "0.3.1", features = ["cuda"] }
dotenv = "0.15.0"
futures = "0.3.29"
hf-hub = "0.3.2"
regex = "1.10.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = "0.9.27"
tokenizers = "0.13.4"
tokio = { version = "1.34.0", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tracing = "0.1.40"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"] }
