cpu: false
use_flash_attn: false
repo_id: "DanielClough/Candle_dolphin-2.2.1-mistral-7b"
model_name: 
model_config: "ChatML"
# repo_id: "DanielClough/Candle_SOLAR-10.7B-Instruct-v1.0"
# model_name: "Candle_SOLAR-10.7B-Instruct-v1.0_q2k.gguf"
# model_config: SolarInstruct
# repo_id: "DanielClough/Candle_MistralLite"
# model_name: "Candle_MistralLite_q2k.gguf"
# model_config: "Amazon"
revision: "main"
tokenizer_file:
weight_files:
quantized: false