name: 'publish macos'

# This will trigger the action on each push to the `release` branch.
on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          # Clone Candle
          cd .. && git clone https://github.com/huggingface/candle.git
          rm -fr candle/.git
          # Rustup
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup target add wasm32-unknown-unknown
          # Download Trunk
          cd ~/.cargo/bin
          curl -L https://github.com/trunk-rs/trunk/releases/download/v0.18.8/trunk-x86_64-apple-darwin.tar.gz | tar xvz

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: tauri
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          prerelease: true
          args: --verbose
